### ISSUE TITLE
Rain forecast

### ISSUE THREAD

**Issue by EarlOfBurton** [ilpiccoli/smart-irrigation#2]
Ciao,
thank you very much for sharing, I'm trying to integrate it into my system! I like the logic a lot!

I have a question:
How is your logic for the rain forecast for the whole day?
As far as I understand I should set OpneWeatherMap to OneCall Hourly, which enables adding mm/h to a 'overall 24h mm'-yesterday value with the helper for the yesterday-sum.

But: The Forecast value that OpenWeatherMap puts out it also an hourly value. So the Rain forecast for this day is only the value for the upcoming hour.
Am I missing something?

Is there a specific reason why you did not set the whole system with daily values?
Thanks a lot & greetings!

**Comment by ilpiccoli** [comment]
Hi, sorry for the late reply.
Yes, the OpenWeatherMap sensor gives me an hourly value, what the automation does is adding every hour that value to an input number that acts as a "Daily Value", and at 23:59 is saved as "Rain Yesterday" and used for the day after.
I would like to use a daily value but OpenWeatherMap doesn't have one and i don't trust much the forecasts, so this is the trick i found and so far it seems to work well.
